// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

export type ObjectReference = {
  id: string;
  kind: string;
  href: string;
  created_at: string | null;
  updated_at: string | null;
};

export type ListMeta = {
  kind: string;
  page: number;
  size: number;
  total: number;
};

export type APIError = {
  id: string;
  kind: string;
  href: string;
  code: string;
  reason: string;
  operation_id: string;
  status_code: number;
};

export class SDKAPIError extends Error {
  readonly statusCode: number;
  readonly code: string;
  readonly reason: string;
  readonly operationId: string;

  constructor(error: APIError) {
    super(`API error ${error.status_code}: ${error.code} - ${error.reason}`);
    this.name = 'SDKAPIError';
    this.statusCode = error.status_code;
    this.code = error.code;
    this.reason = error.reason;
    this.operationId = error.operation_id;
  }
}

export type ListOptions = {
  page?: number;
  size?: number;
  search?: string;
  orderBy?: string;
  fields?: string;
};

export function buildQueryString(opts?: ListOptions): string {
  if (!opts) return '';
  const params = new URLSearchParams();
  if (opts.page !== undefined) params.set('page', String(opts.page));
  if (opts.size !== undefined) params.set('size', String(Math.min(opts.size, 65500)));
  if (opts.search) params.set('search', opts.search);
  if (opts.orderBy) params.set('orderBy', opts.orderBy);
  if (opts.fields) params.set('fields', opts.fields);
  const qs = params.toString();
  return qs ? `?${qs}` : '';
}

export type RequestOptions = {
  signal?: AbortSignal;
};

export type SDKClientConfig = {
  baseUrl?: string;
  token?: string;
  getToken?: () => Promise<string>;
  credentials?: RequestCredentials;
  fetch?: typeof globalThis.fetch;
};

export async function sdkFetch<T>(
  config: SDKClientConfig,
  method: string,
  path: string,
  body?: unknown,
  requestOpts?: RequestOptions,
): Promise<T> {
  const url = `${config.baseUrl ?? ''}/api/hypershell/v1${path}`;
  const headers: Record<string, string> = {};
  const token = config.getToken ? await config.getToken() : config.token;
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json';
  }

  const fetchFn = config.fetch ?? globalThis.fetch;
  const resp = await fetchFn(url, {
    method,
    headers,
    credentials: config.credentials,
    body: body !== undefined ? JSON.stringify(body) : undefined,
    signal: requestOpts?.signal,
  });

  if (!resp.ok) {
    let errorData: APIError;
    try {
      const jsonData = await resp.json();
      if (typeof jsonData === 'object' && jsonData !== null) {
        errorData = {
          id: typeof jsonData.id === 'string' ? jsonData.id : '',
          kind: typeof jsonData.kind === 'string' ? jsonData.kind : 'Error',
          href: typeof jsonData.href === 'string' ? jsonData.href : '',
          code: typeof jsonData.code === 'string' ? jsonData.code : 'unknown_error',
          reason: typeof jsonData.reason === 'string' ? jsonData.reason : `HTTP ${resp.status}: ${resp.statusText}`,
          operation_id: typeof jsonData.operation_id === 'string' ? jsonData.operation_id : '',
          status_code: resp.status,
        };
      } else {
        throw new Error('Invalid error response format');
      }
    } catch {
      errorData = {
        id: '',
        kind: 'Error',
        href: '',
        code: 'unknown_error',
        reason: `HTTP ${resp.status}: ${resp.statusText}`,
        operation_id: '',
        status_code: resp.status,
      };
    }
    throw new SDKAPIError(errorData);
  }

  if (resp.status === 204) {
    return undefined as T;
  }

  return await resp.json();
}
