// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { GatewayRelease, GatewayReleaseList, GatewayReleaseCreateRequest, GatewayReleasePatchRequest } from './gateway_release.js';

export class GatewayReleaseAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: GatewayReleaseCreateRequest, opts?: RequestOptions): Promise<GatewayRelease> {
    return sdkFetch<GatewayRelease>(this.config, 'POST', '/gateway_releases', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<GatewayRelease> {
    return sdkFetch<GatewayRelease>(this.config, 'GET', `/gateway_releases/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<GatewayReleaseList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<GatewayReleaseList>(this.config, 'GET', `/gateway_releases${qs}`, undefined, opts);
  }

  async update(id: string, patch: GatewayReleasePatchRequest, opts?: RequestOptions): Promise<GatewayRelease> {
    return sdkFetch<GatewayRelease>(this.config, 'PATCH', `/gateway_releases/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/gateway_releases/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<GatewayRelease> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
