// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type GatewayNetwork = ObjectReference & {
  hub_gateway_id: string;
  name: string;
  status: string;
  topology: string;
  tunnel_mode: string;
};

export type GatewayNetworkList = ListMeta & {
  items: GatewayNetwork[];
};

export type GatewayNetworkCreateRequest = {
  hub_gateway_id?: string;
  name: string;
  status?: string;
  topology?: string;
  tunnel_mode?: string;
};

export type GatewayNetworkPatchRequest = {
  hub_gateway_id?: string;
  name?: string;
  status?: string;
  topology?: string;
  tunnel_mode?: string;
};

export class GatewayNetworkBuilder {
  private data: Record<string, unknown> = {};


  hubGatewayId(value: string): this {
    this.data['hub_gateway_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  topology(value: string): this {
    this.data['topology'] = value;
    return this;
  }

  tunnelMode(value: string): this {
    this.data['tunnel_mode'] = value;
    return this;
  }

  build(): GatewayNetworkCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as GatewayNetworkCreateRequest;
  }
}

export class GatewayNetworkPatchBuilder {
  private data: Record<string, unknown> = {};


  hubGatewayId(value: string): this {
    this.data['hub_gateway_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  topology(value: string): this {
    this.data['topology'] = value;
    return this;
  }

  tunnelMode(value: string): this {
    this.data['tunnel_mode'] = value;
    return this;
  }

  build(): GatewayNetworkPatchRequest {
    return this.data as GatewayNetworkPatchRequest;
  }
}
