// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { GatewayNetwork, GatewayNetworkList, GatewayNetworkCreateRequest, GatewayNetworkPatchRequest } from './gateway_network.js';

export class GatewayNetworkAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: GatewayNetworkCreateRequest, opts?: RequestOptions): Promise<GatewayNetwork> {
    return sdkFetch<GatewayNetwork>(this.config, 'POST', '/gateway_networks', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<GatewayNetwork> {
    return sdkFetch<GatewayNetwork>(this.config, 'GET', `/gateway_networks/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<GatewayNetworkList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<GatewayNetworkList>(this.config, 'GET', `/gateway_networks${qs}`, undefined, opts);
  }

  async update(id: string, patch: GatewayNetworkPatchRequest, opts?: RequestOptions): Promise<GatewayNetwork> {
    return sdkFetch<GatewayNetwork>(this.config, 'PATCH', `/gateway_networks/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/gateway_networks/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<GatewayNetwork> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
