// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type Gateway = ObjectReference & {
  active_sandbox_count: number;
  cluster_id: string;
  console_address: string;
  created_by: string;
  credential_driver: string;
  external_dns: string;
  gateway_version: string;
  image: string;
  name: string;
  namespace: string;
  observed_release_id: string;
  oidc: string;
  phase: string;
  provisioning_conditions: string;
  release_id: string;
  route: string;
  route_address: string;
  server_dns_names: string;
  service_type: string;
  status: string;
  supervisor_image: string;
  tls_mode: string;
};

export type GatewayList = ListMeta & {
  items: Gateway[];
};

export type GatewayCreateRequest = {
  cluster_id: string;
  credential_driver?: string;
  external_dns?: string;
  image?: string;
  name: string;
  phase?: string;
  release_id: string;
  route?: string;
  server_dns_names?: string;
  service_type?: string;
  status?: string;
  supervisor_image?: string;
  tls_mode?: string;
};

export type GatewayPatchRequest = {
  cluster_id?: string;
  credential_driver?: string;
  external_dns?: string;
  image?: string;
  name?: string;
  oidc?: string;
  phase?: string;
  release_id?: string;
  route?: string;
  route_address?: string;
  server_dns_names?: string;
  service_type?: string;
  status?: string;
  supervisor_image?: string;
  tls_mode?: string;
};

export class GatewayBuilder {
  private data: Record<string, unknown> = {};


  clusterId(value: string): this {
    this.data['cluster_id'] = value;
    return this;
  }

  credentialDriver(value: string): this {
    this.data['credential_driver'] = value;
    return this;
  }

  externalDns(value: string): this {
    this.data['external_dns'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  releaseId(value: string): this {
    this.data['release_id'] = value;
    return this;
  }

  route(value: string): this {
    this.data['route'] = value;
    return this;
  }

  serverDnsNames(value: string): this {
    this.data['server_dns_names'] = value;
    return this;
  }

  serviceType(value: string): this {
    this.data['service_type'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  supervisorImage(value: string): this {
    this.data['supervisor_image'] = value;
    return this;
  }

  tlsMode(value: string): this {
    this.data['tls_mode'] = value;
    return this;
  }

  build(): GatewayCreateRequest {
    if (!this.data['cluster_id']) {
      throw new Error('cluster_id is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['namespace']) {
      throw new Error('namespace is required');
    }
    if (!this.data['release_id']) {
      throw new Error('release_id is required');
    }
    return this.data as GatewayCreateRequest;
  }
}

export class GatewayPatchBuilder {
  private data: Record<string, unknown> = {};


  clusterId(value: string): this {
    this.data['cluster_id'] = value;
    return this;
  }

  credentialDriver(value: string): this {
    this.data['credential_driver'] = value;
    return this;
  }

  externalDns(value: string): this {
    this.data['external_dns'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  oidc(value: string): this {
    this.data['oidc'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  releaseId(value: string): this {
    this.data['release_id'] = value;
    return this;
  }

  route(value: string): this {
    this.data['route'] = value;
    return this;
  }

  routeAddress(value: string): this {
    this.data['route_address'] = value;
    return this;
  }

  serverDnsNames(value: string): this {
    this.data['server_dns_names'] = value;
    return this;
  }

  serviceType(value: string): this {
    this.data['service_type'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  supervisorImage(value: string): this {
    this.data['supervisor_image'] = value;
    return this;
  }

  tlsMode(value: string): this {
    this.data['tls_mode'] = value;
    return this;
  }

  build(): GatewayPatchRequest {
    return this.data as GatewayPatchRequest;
  }
}
