// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type GatewayRelease = ObjectReference & {
  canary_duration: string;
  canary_percent: number;
  image: string;
  name: string;
  rollout_strategy: string;
  status: string;
};

export type GatewayReleaseList = ListMeta & {
  items: GatewayRelease[];
};

export type GatewayReleaseCreateRequest = {
  canary_duration?: string;
  canary_percent?: number;
  image: string;
  name: string;
  rollout_strategy?: string;
  status?: string;
};

export type GatewayReleasePatchRequest = {
  canary_duration?: string;
  canary_percent?: number;
  image?: string;
  name?: string;
  rollout_strategy?: string;
  status?: string;
};

export class GatewayReleaseBuilder {
  private data: Record<string, unknown> = {};


  canaryDuration(value: string): this {
    this.data['canary_duration'] = value;
    return this;
  }

  canaryPercent(value: number): this {
    this.data['canary_percent'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  rolloutStrategy(value: string): this {
    this.data['rollout_strategy'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): GatewayReleaseCreateRequest {
    if (!this.data['image']) {
      throw new Error('image is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as GatewayReleaseCreateRequest;
  }
}

export class GatewayReleasePatchBuilder {
  private data: Record<string, unknown> = {};


  canaryDuration(value: string): this {
    this.data['canary_duration'] = value;
    return this;
  }

  canaryPercent(value: number): this {
    this.data['canary_percent'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  rolloutStrategy(value: string): this {
    this.data['rollout_strategy'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): GatewayReleasePatchRequest {
    return this.data as GatewayReleasePatchRequest;
  }
}
