// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { ManagedCluster, ManagedClusterList, ManagedClusterCreateRequest, ManagedClusterPatchRequest } from './managed_cluster.js';

export class ManagedClusterAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: ManagedClusterCreateRequest, opts?: RequestOptions): Promise<ManagedCluster> {
    return sdkFetch<ManagedCluster>(this.config, 'POST', '/managed_clusters', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ManagedCluster> {
    return sdkFetch<ManagedCluster>(this.config, 'GET', `/managed_clusters/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ManagedClusterList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<ManagedClusterList>(this.config, 'GET', `/managed_clusters${qs}`, undefined, opts);
  }

  async update(id: string, patch: ManagedClusterPatchRequest, opts?: RequestOptions): Promise<ManagedCluster> {
    return sdkFetch<ManagedCluster>(this.config, 'PATCH', `/managed_clusters/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/managed_clusters/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ManagedCluster> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
