// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type ManagedCluster = ObjectReference & {
  api_server_url: string;
  kubeconfig_secret: string;
  last_seen_at: string;
  name: string;
  oidc_subject: string;
  provider: string;
  region: string;
  status: string;
};

export type ManagedClusterList = ListMeta & {
  items: ManagedCluster[];
};

export type ManagedClusterCreateRequest = {
  api_server_url?: string;
  kubeconfig_secret: string;
  name: string;
  provider: string;
  region?: string;
  status?: string;
};

export type ManagedClusterPatchRequest = {
  api_server_url?: string;
  kubeconfig_secret?: string;
  name?: string;
  provider?: string;
  region?: string;
  status?: string;
};

export class ManagedClusterBuilder {
  private data: Record<string, unknown> = {};


  apiServerUrl(value: string): this {
    this.data['api_server_url'] = value;
    return this;
  }

  kubeconfigSecret(value: string): this {
    this.data['kubeconfig_secret'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  region(value: string): this {
    this.data['region'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ManagedClusterCreateRequest {
    if (!this.data['kubeconfig_secret']) {
      throw new Error('kubeconfig_secret is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['provider']) {
      throw new Error('provider is required');
    }
    return this.data as ManagedClusterCreateRequest;
  }
}

export class ManagedClusterPatchBuilder {
  private data: Record<string, unknown> = {};


  apiServerUrl(value: string): this {
    this.data['api_server_url'] = value;
    return this;
  }

  kubeconfigSecret(value: string): this {
    this.data['kubeconfig_secret'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  region(value: string): this {
    this.data['region'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ManagedClusterPatchRequest {
    return this.data as ManagedClusterPatchRequest;
  }
}
