// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { SDKClientConfig, RequestOptions } from './base.js';
import { sdkFetch } from './base.js';
import type {
  OpenShellGatewayServiceAccountCreateRequest,
  OpenShellGatewayServiceAccountCreateResponse,
  OpenShellGatewayServiceAccountGetResponse,
  OpenShellGatewayServiceAccountListItem,
  OpenShellGatewayServiceAccountList,
  OpenShellGatewayServiceAccountListOptions,
} from './open_shell_gateway_service_account.js';

export class OpenShellGatewayServiceAccountAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(gatewayId: string, data: OpenShellGatewayServiceAccountCreateRequest, opts?: RequestOptions): Promise<OpenShellGatewayServiceAccountCreateResponse> {
    return sdkFetch<OpenShellGatewayServiceAccountCreateResponse>(this.config, 'POST', `/gateways/${encodeURIComponent(gatewayId)}/service_accounts`, data, opts);
  }

  async get(gatewayId: string, serviceAccountId: string, opts?: RequestOptions): Promise<OpenShellGatewayServiceAccountGetResponse> {
    return sdkFetch<OpenShellGatewayServiceAccountGetResponse>(this.config, 'GET', `/gateways/${encodeURIComponent(gatewayId)}/service_accounts/${encodeURIComponent(serviceAccountId)}`, undefined, opts);
  }

  async list(gatewayId: string, listOpts?: OpenShellGatewayServiceAccountListOptions, opts?: RequestOptions): Promise<OpenShellGatewayServiceAccountList> {
    const params = new URLSearchParams();
    if (listOpts?.page !== undefined) {
      params.set('page', String(listOpts.page));
    }
    if (listOpts?.size !== undefined) {
      params.set('size', String(Math.min(listOpts.size, 100)));
    }
    if (listOpts?.status !== undefined) {
      params.set('status', String(listOpts.status));
    }
    if (listOpts?.search !== undefined && listOpts.search !== '') {
      params.set('search', String(listOpts.search));
    }
    if (listOpts?.sort !== undefined) {
      params.set('sort', String(listOpts.sort));
    }
    if (listOpts?.order !== undefined) {
      params.set('order', String(listOpts.order));
    }
    const query = params.toString();
    const path = `/gateways/${encodeURIComponent(gatewayId)}/service_accounts` + (query ? `?${query}` : '');
    return sdkFetch<OpenShellGatewayServiceAccountList>(this.config, 'GET', path, undefined, opts);
  }

  async revoke(gatewayId: string, serviceAccountId: string, opts?: RequestOptions): Promise<OpenShellGatewayServiceAccountListItem> {
    return sdkFetch<OpenShellGatewayServiceAccountListItem>(this.config, 'POST', `/gateways/${encodeURIComponent(gatewayId)}/service_accounts/${encodeURIComponent(serviceAccountId)}` + '/revoke', undefined, opts);
  }

  async delete(gatewayId: string, serviceAccountId: string, opts?: RequestOptions): Promise<OpenShellGatewayServiceAccountListItem | undefined> {
    return sdkFetch<OpenShellGatewayServiceAccountListItem | undefined>(this.config, 'DELETE', `/gateways/${encodeURIComponent(gatewayId)}/service_accounts/${encodeURIComponent(serviceAccountId)}`, undefined, opts);
  }

  async *listAll(gatewayId: string, size: number = 20, opts?: RequestOptions): AsyncGenerator<OpenShellGatewayServiceAccountListItem> {
    let page = 1;
    while (true) {
      const result = await this.list(gatewayId, { page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
