// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917


export type OpenShellGatewayServiceAccountCapabilities = {
  allowed_roles: OpenShellGatewayServiceAccountRole[];
  can_create: boolean;
  can_manage_all: boolean;
  expiration_policy: OpenShellGatewayServiceAccountExpirationPolicy;
};



export type OpenShellGatewayServiceAccountConnection = {
  access_token_lifetime_seconds: number;
  audience: string;
  client_id: string;
  gateway_endpoint?: string;
  gateway_name: string;
  grant_type: "client_credentials";
  issuer: string;
  token_endpoint: string;
};



export type OpenShellGatewayServiceAccountCreateRequest = {
  credential_type?: "client_secret";
  description?: string | null;
  expires_at?: string;
  name: string;
  role?: OpenShellGatewayServiceAccountRole;
};



export type OpenShellGatewayServiceAccountCreateResponse = {
  client_id: string;
  created_at: string;
  created_by_user_id: string;
  credential: OpenShellGatewayServiceAccountCredential;
  credential_type: "client_secret";
  description?: string | null;
  expires_at: string;
  gateway_id: string;
  id: string;
  last_error?: string | null;
  name: string;
  revoked_at?: string | null;
  role: OpenShellGatewayServiceAccountRole;
  status: OpenShellGatewayServiceAccountStatus;
  subject: string;
  updated_at: string;
};



export type OpenShellGatewayServiceAccountCredential = {
  access_token_lifetime_seconds: number;
  audience: string;
  client_id: string;
  client_secret: string;
  gateway_endpoint?: string;
  gateway_name: string;
  grant_type: "client_credentials";
  issuer: string;
  token_endpoint: string;
};



export type OpenShellGatewayServiceAccountExpirationPolicy = {
  default_seconds: number;
  maximum_seconds: number;
  minimum_seconds: number;
};



export type OpenShellGatewayServiceAccountGetResponse = {
  client_id: string;
  connection: OpenShellGatewayServiceAccountConnection;
  created_at: string;
  created_by_user_id: string;
  credential_type: "client_secret";
  description?: string | null;
  expires_at: string;
  gateway_id: string;
  id: string;
  last_error?: string | null;
  name: string;
  revoked_at?: string | null;
  role: OpenShellGatewayServiceAccountRole;
  status: OpenShellGatewayServiceAccountStatus;
  subject: string;
  updated_at: string;
};



export type OpenShellGatewayServiceAccountList = {
  capabilities: OpenShellGatewayServiceAccountCapabilities;
  items: OpenShellGatewayServiceAccountListItem[];
  page: number;
  size: number;
  total: number;
};



export type OpenShellGatewayServiceAccountListItem = {
  client_id: string;
  created_at: string;
  created_by_user_id: string;
  credential_type: "client_secret";
  description?: string | null;
  expires_at: string;
  gateway_id: string;
  id: string;
  last_error?: string | null;
  name: string;
  revoked_at?: string | null;
  role: OpenShellGatewayServiceAccountRole;
  status: OpenShellGatewayServiceAccountStatus;
  subject: string;
  updated_at: string;
};



export type OpenShellGatewayServiceAccountRole = 'openshell-user' | 'openshell-admin';



export type OpenShellGatewayServiceAccountStatus = 'provisioning' | 'ready' | 'degraded' | 'expired' | 'revoking' | 'revoked' | 'deleting' | 'error';


export type OpenShellGatewayServiceAccountListOptions = {
  page?: number;
  size?: number;
  status?: OpenShellGatewayServiceAccountStatus;
  search?: string;
  sort?: "name" | "role" | "status" | "expires_at" | "created_at";
  order?: "asc" | "desc";
};
