// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type Role = ObjectReference & {
  built_in: boolean;
  description: string;
  display_name: string;
  name: string;
  permissions: string;
};

export type RoleList = ListMeta & {
  items: Role[];
};

export type RoleCreateRequest = {
  built_in?: boolean;
  description?: string;
  display_name?: string;
  name: string;
  permissions?: string;
};

export type RolePatchRequest = {
};

export class RoleBuilder {
  private data: Record<string, unknown> = {};


  builtIn(value: boolean): this {
    this.data['built_in'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  permissions(value: string): this {
    this.data['permissions'] = value;
    return this;
  }

  build(): RoleCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as RoleCreateRequest;
  }
}

export class RolePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): RolePatchRequest {
    return this.data as RolePatchRequest;
  }
}
