// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { RoleBinding, RoleBindingList, RoleBindingCreateRequest } from './role_binding.js';

export class RoleBindingAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: RoleBindingCreateRequest, opts?: RequestOptions): Promise<RoleBinding> {
    return sdkFetch<RoleBinding>(this.config, 'POST', '/role_bindings', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<RoleBinding> {
    return sdkFetch<RoleBinding>(this.config, 'GET', `/role_bindings/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<RoleBindingList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<RoleBindingList>(this.config, 'GET', `/role_bindings${qs}`, undefined, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/role_bindings/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<RoleBinding> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
