// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

import type { ObjectReference, ListMeta } from './base.js';

export type RoleBinding = ObjectReference & {
  gateway_id: string;
  role_id: string;
  scope: string;
  user_id: string;
};

export type RoleBindingList = ListMeta & {
  items: RoleBinding[];
};

export type RoleBindingCreateRequest = {
  gateway_id?: string;
  role_id: string;
  scope: string;
  user_id?: string;
};

export type RoleBindingPatchRequest = {
};

export class RoleBindingBuilder {
  private data: Record<string, unknown> = {};


  gatewayId(value: string): this {
    this.data['gateway_id'] = value;
    return this;
  }

  roleId(value: string): this {
    this.data['role_id'] = value;
    return this;
  }

  scope(value: string): this {
    this.data['scope'] = value;
    return this;
  }

  userId(value: string): this {
    this.data['user_id'] = value;
    return this;
  }

  build(): RoleBindingCreateRequest {
    if (!this.data['role_id']) {
      throw new Error('role_id is required');
    }
    if (!this.data['scope']) {
      throw new Error('scope is required');
    }
    return this.data as RoleBindingCreateRequest;
  }
}

export class RoleBindingPatchBuilder {
  private data: Record<string, unknown> = {};


  build(): RoleBindingPatchRequest {
    return this.data as RoleBindingPatchRequest;
  }
}
