/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GatewayCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayCreateRequest{}

// GatewayCreateRequest struct for GatewayCreateRequest
type GatewayCreateRequest struct {
	Name        string  `json:"name"`
	ClusterId   string  `json:"cluster_id"`
	ReleaseId   string  `json:"release_id"`
	ExternalDns *string `json:"external_dns,omitempty"`
	TlsMode     *string `json:"tls_mode,omitempty"`
	ServiceType *string `json:"service_type,omitempty"`
	Status      *string `json:"status,omitempty"`
	Phase       *string `json:"phase,omitempty"`
	// Container image for the gateway deployment
	Image *string `json:"image,omitempty"`
	// Container image for the supervisor sidecar
	SupervisorImage *string `json:"supervisor_image,omitempty"`
	// DNS names for TLS certificate SANs
	ServerDnsNames []string `json:"server_dns_names,omitempty"`
	// JSON-encoded OIDC authentication configuration
	Oidc *string `json:"oidc,omitempty"`
	// JSON-encoded route configuration
	Route *string `json:"route,omitempty"`
	// JSON-encoded credential storage driver configuration
	CredentialDriver *string `json:"credential_driver,omitempty"`
}

type _GatewayCreateRequest GatewayCreateRequest

// NewGatewayCreateRequest instantiates a new GatewayCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayCreateRequest(name string, clusterId string, releaseId string) *GatewayCreateRequest {
	this := GatewayCreateRequest{}
	this.Name = name
	this.ClusterId = clusterId
	this.ReleaseId = releaseId
	return &this
}

// NewGatewayCreateRequestWithDefaults instantiates a new GatewayCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayCreateRequestWithDefaults() *GatewayCreateRequest {
	this := GatewayCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *GatewayCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewayCreateRequest) SetName(v string) {
	o.Name = v
}

// GetClusterId returns the ClusterId field value
func (o *GatewayCreateRequest) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *GatewayCreateRequest) SetClusterId(v string) {
	o.ClusterId = v
}

// GetReleaseId returns the ReleaseId field value
func (o *GatewayCreateRequest) GetReleaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseId
}

// GetReleaseIdOk returns a tuple with the ReleaseId field value
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetReleaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseId, true
}

// SetReleaseId sets field value
func (o *GatewayCreateRequest) SetReleaseId(v string) {
	o.ReleaseId = v
}

// GetExternalDns returns the ExternalDns field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetExternalDns() string {
	if o == nil || IsNil(o.ExternalDns) {
		var ret string
		return ret
	}
	return *o.ExternalDns
}

// GetExternalDnsOk returns a tuple with the ExternalDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetExternalDnsOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalDns) {
		return nil, false
	}
	return o.ExternalDns, true
}

// HasExternalDns returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasExternalDns() bool {
	if o != nil && !IsNil(o.ExternalDns) {
		return true
	}

	return false
}

// SetExternalDns gets a reference to the given string and assigns it to the ExternalDns field.
func (o *GatewayCreateRequest) SetExternalDns(v string) {
	o.ExternalDns = &v
}

// GetTlsMode returns the TlsMode field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetTlsMode() string {
	if o == nil || IsNil(o.TlsMode) {
		var ret string
		return ret
	}
	return *o.TlsMode
}

// GetTlsModeOk returns a tuple with the TlsMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetTlsModeOk() (*string, bool) {
	if o == nil || IsNil(o.TlsMode) {
		return nil, false
	}
	return o.TlsMode, true
}

// HasTlsMode returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasTlsMode() bool {
	if o != nil && !IsNil(o.TlsMode) {
		return true
	}

	return false
}

// SetTlsMode gets a reference to the given string and assigns it to the TlsMode field.
func (o *GatewayCreateRequest) SetTlsMode(v string) {
	o.TlsMode = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *GatewayCreateRequest) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GatewayCreateRequest) SetStatus(v string) {
	o.Status = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *GatewayCreateRequest) SetPhase(v string) {
	o.Phase = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *GatewayCreateRequest) SetImage(v string) {
	o.Image = &v
}

// GetSupervisorImage returns the SupervisorImage field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetSupervisorImage() string {
	if o == nil || IsNil(o.SupervisorImage) {
		var ret string
		return ret
	}
	return *o.SupervisorImage
}

// GetSupervisorImageOk returns a tuple with the SupervisorImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetSupervisorImageOk() (*string, bool) {
	if o == nil || IsNil(o.SupervisorImage) {
		return nil, false
	}
	return o.SupervisorImage, true
}

// HasSupervisorImage returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasSupervisorImage() bool {
	if o != nil && !IsNil(o.SupervisorImage) {
		return true
	}

	return false
}

// SetSupervisorImage gets a reference to the given string and assigns it to the SupervisorImage field.
func (o *GatewayCreateRequest) SetSupervisorImage(v string) {
	o.SupervisorImage = &v
}

// GetServerDnsNames returns the ServerDnsNames field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetServerDnsNames() []string {
	if o == nil || IsNil(o.ServerDnsNames) {
		var ret []string
		return ret
	}
	return o.ServerDnsNames
}

// GetServerDnsNamesOk returns a tuple with the ServerDnsNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetServerDnsNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerDnsNames) {
		return nil, false
	}
	return o.ServerDnsNames, true
}

// HasServerDnsNames returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasServerDnsNames() bool {
	if o != nil && !IsNil(o.ServerDnsNames) {
		return true
	}

	return false
}

// SetServerDnsNames gets a reference to the given []string and assigns it to the ServerDnsNames field.
func (o *GatewayCreateRequest) SetServerDnsNames(v []string) {
	o.ServerDnsNames = v
}

// GetOidc returns the Oidc field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetOidc() string {
	if o == nil || IsNil(o.Oidc) {
		var ret string
		return ret
	}
	return *o.Oidc
}

// GetOidcOk returns a tuple with the Oidc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetOidcOk() (*string, bool) {
	if o == nil || IsNil(o.Oidc) {
		return nil, false
	}
	return o.Oidc, true
}

// HasOidc returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasOidc() bool {
	if o != nil && !IsNil(o.Oidc) {
		return true
	}

	return false
}

// SetOidc gets a reference to the given string and assigns it to the Oidc field.
func (o *GatewayCreateRequest) SetOidc(v string) {
	o.Oidc = &v
}

// GetRoute returns the Route field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetRoute() string {
	if o == nil || IsNil(o.Route) {
		var ret string
		return ret
	}
	return *o.Route
}

// GetRouteOk returns a tuple with the Route field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetRouteOk() (*string, bool) {
	if o == nil || IsNil(o.Route) {
		return nil, false
	}
	return o.Route, true
}

// HasRoute returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasRoute() bool {
	if o != nil && !IsNil(o.Route) {
		return true
	}

	return false
}

// SetRoute gets a reference to the given string and assigns it to the Route field.
func (o *GatewayCreateRequest) SetRoute(v string) {
	o.Route = &v
}

// GetCredentialDriver returns the CredentialDriver field value if set, zero value otherwise.
func (o *GatewayCreateRequest) GetCredentialDriver() string {
	if o == nil || IsNil(o.CredentialDriver) {
		var ret string
		return ret
	}
	return *o.CredentialDriver
}

// GetCredentialDriverOk returns a tuple with the CredentialDriver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayCreateRequest) GetCredentialDriverOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialDriver) {
		return nil, false
	}
	return o.CredentialDriver, true
}

// HasCredentialDriver returns a boolean if a field has been set.
func (o *GatewayCreateRequest) HasCredentialDriver() bool {
	if o != nil && !IsNil(o.CredentialDriver) {
		return true
	}

	return false
}

// SetCredentialDriver gets a reference to the given string and assigns it to the CredentialDriver field.
func (o *GatewayCreateRequest) SetCredentialDriver(v string) {
	o.CredentialDriver = &v
}

func (o GatewayCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cluster_id"] = o.ClusterId
	toSerialize["release_id"] = o.ReleaseId
	if !IsNil(o.ExternalDns) {
		toSerialize["external_dns"] = o.ExternalDns
	}
	if !IsNil(o.TlsMode) {
		toSerialize["tls_mode"] = o.TlsMode
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.SupervisorImage) {
		toSerialize["supervisor_image"] = o.SupervisorImage
	}
	if !IsNil(o.ServerDnsNames) {
		toSerialize["server_dns_names"] = o.ServerDnsNames
	}
	if !IsNil(o.Oidc) {
		toSerialize["oidc"] = o.Oidc
	}
	if !IsNil(o.Route) {
		toSerialize["route"] = o.Route
	}
	if !IsNil(o.CredentialDriver) {
		toSerialize["credential_driver"] = o.CredentialDriver
	}
	return toSerialize, nil
}

func (o *GatewayCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"cluster_id",
		"release_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayCreateRequest := _GatewayCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayCreateRequest)

	if err != nil {
		return err
	}

	*o = GatewayCreateRequest(varGatewayCreateRequest)

	return err
}

type NullableGatewayCreateRequest struct {
	value *GatewayCreateRequest
	isSet bool
}

func (v NullableGatewayCreateRequest) Get() *GatewayCreateRequest {
	return v.value
}

func (v *NullableGatewayCreateRequest) Set(val *GatewayCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayCreateRequest(val *GatewayCreateRequest) *NullableGatewayCreateRequest {
	return &NullableGatewayCreateRequest{value: val, isSet: true}
}

func (v NullableGatewayCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
