/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GatewayPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayPatchRequest{}

// GatewayPatchRequest struct for GatewayPatchRequest
type GatewayPatchRequest struct {
	Name             *string  `json:"name,omitempty"`
	ClusterId        *string  `json:"cluster_id,omitempty"`
	ReleaseId        *string  `json:"release_id,omitempty"`
	ExternalDns      *string  `json:"external_dns,omitempty"`
	TlsMode          *string  `json:"tls_mode,omitempty"`
	ServiceType      *string  `json:"service_type,omitempty"`
	Status           *string  `json:"status,omitempty"`
	Phase            *string  `json:"phase,omitempty"`
	Image            *string  `json:"image,omitempty"`
	SupervisorImage  *string  `json:"supervisor_image,omitempty"`
	ServerDnsNames   []string `json:"server_dns_names,omitempty"`
	RouteAddress     *string  `json:"route_address,omitempty"`
	Oidc             *string  `json:"oidc,omitempty"`
	Route            *string  `json:"route,omitempty"`
	CredentialDriver *string  `json:"credential_driver,omitempty"`
}

// NewGatewayPatchRequest instantiates a new GatewayPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayPatchRequest() *GatewayPatchRequest {
	this := GatewayPatchRequest{}
	return &this
}

// NewGatewayPatchRequestWithDefaults instantiates a new GatewayPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayPatchRequestWithDefaults() *GatewayPatchRequest {
	this := GatewayPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GatewayPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetClusterId() string {
	if o == nil || IsNil(o.ClusterId) {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *GatewayPatchRequest) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetReleaseId returns the ReleaseId field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetReleaseId() string {
	if o == nil || IsNil(o.ReleaseId) {
		var ret string
		return ret
	}
	return *o.ReleaseId
}

// GetReleaseIdOk returns a tuple with the ReleaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetReleaseIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseId) {
		return nil, false
	}
	return o.ReleaseId, true
}

// HasReleaseId returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasReleaseId() bool {
	if o != nil && !IsNil(o.ReleaseId) {
		return true
	}

	return false
}

// SetReleaseId gets a reference to the given string and assigns it to the ReleaseId field.
func (o *GatewayPatchRequest) SetReleaseId(v string) {
	o.ReleaseId = &v
}

// GetExternalDns returns the ExternalDns field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetExternalDns() string {
	if o == nil || IsNil(o.ExternalDns) {
		var ret string
		return ret
	}
	return *o.ExternalDns
}

// GetExternalDnsOk returns a tuple with the ExternalDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetExternalDnsOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalDns) {
		return nil, false
	}
	return o.ExternalDns, true
}

// HasExternalDns returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasExternalDns() bool {
	if o != nil && !IsNil(o.ExternalDns) {
		return true
	}

	return false
}

// SetExternalDns gets a reference to the given string and assigns it to the ExternalDns field.
func (o *GatewayPatchRequest) SetExternalDns(v string) {
	o.ExternalDns = &v
}

// GetTlsMode returns the TlsMode field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetTlsMode() string {
	if o == nil || IsNil(o.TlsMode) {
		var ret string
		return ret
	}
	return *o.TlsMode
}

// GetTlsModeOk returns a tuple with the TlsMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetTlsModeOk() (*string, bool) {
	if o == nil || IsNil(o.TlsMode) {
		return nil, false
	}
	return o.TlsMode, true
}

// HasTlsMode returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasTlsMode() bool {
	if o != nil && !IsNil(o.TlsMode) {
		return true
	}

	return false
}

// SetTlsMode gets a reference to the given string and assigns it to the TlsMode field.
func (o *GatewayPatchRequest) SetTlsMode(v string) {
	o.TlsMode = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *GatewayPatchRequest) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GatewayPatchRequest) SetStatus(v string) {
	o.Status = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *GatewayPatchRequest) SetPhase(v string) {
	o.Phase = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *GatewayPatchRequest) SetImage(v string) {
	o.Image = &v
}

// GetSupervisorImage returns the SupervisorImage field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetSupervisorImage() string {
	if o == nil || IsNil(o.SupervisorImage) {
		var ret string
		return ret
	}
	return *o.SupervisorImage
}

// GetSupervisorImageOk returns a tuple with the SupervisorImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetSupervisorImageOk() (*string, bool) {
	if o == nil || IsNil(o.SupervisorImage) {
		return nil, false
	}
	return o.SupervisorImage, true
}

// HasSupervisorImage returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasSupervisorImage() bool {
	if o != nil && !IsNil(o.SupervisorImage) {
		return true
	}

	return false
}

// SetSupervisorImage gets a reference to the given string and assigns it to the SupervisorImage field.
func (o *GatewayPatchRequest) SetSupervisorImage(v string) {
	o.SupervisorImage = &v
}

// GetServerDnsNames returns the ServerDnsNames field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetServerDnsNames() []string {
	if o == nil || IsNil(o.ServerDnsNames) {
		var ret []string
		return ret
	}
	return o.ServerDnsNames
}

// GetServerDnsNamesOk returns a tuple with the ServerDnsNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetServerDnsNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerDnsNames) {
		return nil, false
	}
	return o.ServerDnsNames, true
}

// HasServerDnsNames returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasServerDnsNames() bool {
	if o != nil && !IsNil(o.ServerDnsNames) {
		return true
	}

	return false
}

// SetServerDnsNames gets a reference to the given []string and assigns it to the ServerDnsNames field.
func (o *GatewayPatchRequest) SetServerDnsNames(v []string) {
	o.ServerDnsNames = v
}

// GetRouteAddress returns the RouteAddress field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetRouteAddress() string {
	if o == nil || IsNil(o.RouteAddress) {
		var ret string
		return ret
	}
	return *o.RouteAddress
}

// GetRouteAddressOk returns a tuple with the RouteAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetRouteAddressOk() (*string, bool) {
	if o == nil || IsNil(o.RouteAddress) {
		return nil, false
	}
	return o.RouteAddress, true
}

// HasRouteAddress returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasRouteAddress() bool {
	if o != nil && !IsNil(o.RouteAddress) {
		return true
	}

	return false
}

// SetRouteAddress gets a reference to the given string and assigns it to the RouteAddress field.
func (o *GatewayPatchRequest) SetRouteAddress(v string) {
	o.RouteAddress = &v
}

// GetOidc returns the Oidc field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetOidc() string {
	if o == nil || IsNil(o.Oidc) {
		var ret string
		return ret
	}
	return *o.Oidc
}

// GetOidcOk returns a tuple with the Oidc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetOidcOk() (*string, bool) {
	if o == nil || IsNil(o.Oidc) {
		return nil, false
	}
	return o.Oidc, true
}

// HasOidc returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasOidc() bool {
	if o != nil && !IsNil(o.Oidc) {
		return true
	}

	return false
}

// SetOidc gets a reference to the given string and assigns it to the Oidc field.
func (o *GatewayPatchRequest) SetOidc(v string) {
	o.Oidc = &v
}

// GetRoute returns the Route field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetRoute() string {
	if o == nil || IsNil(o.Route) {
		var ret string
		return ret
	}
	return *o.Route
}

// GetRouteOk returns a tuple with the Route field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetRouteOk() (*string, bool) {
	if o == nil || IsNil(o.Route) {
		return nil, false
	}
	return o.Route, true
}

// HasRoute returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasRoute() bool {
	if o != nil && !IsNil(o.Route) {
		return true
	}

	return false
}

// SetRoute gets a reference to the given string and assigns it to the Route field.
func (o *GatewayPatchRequest) SetRoute(v string) {
	o.Route = &v
}

// GetCredentialDriver returns the CredentialDriver field value if set, zero value otherwise.
func (o *GatewayPatchRequest) GetCredentialDriver() string {
	if o == nil || IsNil(o.CredentialDriver) {
		var ret string
		return ret
	}
	return *o.CredentialDriver
}

// GetCredentialDriverOk returns a tuple with the CredentialDriver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatchRequest) GetCredentialDriverOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialDriver) {
		return nil, false
	}
	return o.CredentialDriver, true
}

// HasCredentialDriver returns a boolean if a field has been set.
func (o *GatewayPatchRequest) HasCredentialDriver() bool {
	if o != nil && !IsNil(o.CredentialDriver) {
		return true
	}

	return false
}

// SetCredentialDriver gets a reference to the given string and assigns it to the CredentialDriver field.
func (o *GatewayPatchRequest) SetCredentialDriver(v string) {
	o.CredentialDriver = &v
}

func (o GatewayPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !IsNil(o.ReleaseId) {
		toSerialize["release_id"] = o.ReleaseId
	}
	if !IsNil(o.ExternalDns) {
		toSerialize["external_dns"] = o.ExternalDns
	}
	if !IsNil(o.TlsMode) {
		toSerialize["tls_mode"] = o.TlsMode
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.SupervisorImage) {
		toSerialize["supervisor_image"] = o.SupervisorImage
	}
	if !IsNil(o.ServerDnsNames) {
		toSerialize["server_dns_names"] = o.ServerDnsNames
	}
	if !IsNil(o.RouteAddress) {
		toSerialize["route_address"] = o.RouteAddress
	}
	if !IsNil(o.Oidc) {
		toSerialize["oidc"] = o.Oidc
	}
	if !IsNil(o.Route) {
		toSerialize["route"] = o.Route
	}
	if !IsNil(o.CredentialDriver) {
		toSerialize["credential_driver"] = o.CredentialDriver
	}
	return toSerialize, nil
}

type NullableGatewayPatchRequest struct {
	value *GatewayPatchRequest
	isSet bool
}

func (v NullableGatewayPatchRequest) Get() *GatewayPatchRequest {
	return v.value
}

func (v *NullableGatewayPatchRequest) Set(val *GatewayPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayPatchRequest(val *GatewayPatchRequest) *NullableGatewayPatchRequest {
	return &NullableGatewayPatchRequest{value: val, isSet: true}
}

func (v NullableGatewayPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
