/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Gateway type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Gateway{}

// Gateway struct for Gateway
type Gateway struct {
	Id        *string    `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	Href      *string    `json:"href,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Name      string     `json:"name"`
	ClusterId string     `json:"cluster_id"`
	ReleaseId string     `json:"release_id"`
	// API-assigned Kubernetes namespace derived from the Gateway identifier
	Namespace   string  `json:"namespace"`
	ExternalDns *string `json:"external_dns,omitempty"`
	TlsMode     *string `json:"tls_mode,omitempty"`
	ServiceType *string `json:"service_type,omitempty"`
	Status      *string `json:"status,omitempty"`
	Phase       *string `json:"phase,omitempty"`
	// Container image for the gateway deployment
	Image *string `json:"image,omitempty"`
	// Container image for the supervisor sidecar
	SupervisorImage *string `json:"supervisor_image,omitempty"`
	// DNS names for TLS certificate SANs
	ServerDnsNames []string `json:"server_dns_names,omitempty"`
	// External route address populated by the control plane
	RouteAddress *string `json:"route_address,omitempty"`
	// Web console address populated by the control plane
	ConsoleAddress *string `json:"console_address,omitempty"`
	// Runtime version from the last successful gateway health response
	GatewayVersion *string `json:"gateway_version,omitempty"`
	// Release the control plane has rolled out and observed healthy, advanced only after a new revision passes its health gates; distinct from the desired release_id and populated by the control plane
	ObservedReleaseId *string `json:"observed_release_id,omitempty"`
	// JSON-encoded OIDC authentication configuration (auto-populated by Keycloak provisioning)
	Oidc *string `json:"oidc,omitempty"`
	// JSON-encoded route configuration
	Route *string `json:"route,omitempty"`
	// JSON-encoded credential storage driver configuration
	CredentialDriver *string `json:"credential_driver,omitempty"`
	// Number of active (Running or Pending) agent sandboxes observed in the gateway namespace by the control plane
	ActiveSandboxCount *int32 `json:"active_sandbox_count,omitempty"`
	// Ordered list of provisioning conditions describing sub-phase progress
	ProvisioningConditions []GatewayAllOfProvisioningConditions `json:"provisioning_conditions,omitempty"`
	// Username of the user who provisioned this gateway, resolved from RBAC role bindings
	CreatedBy *string `json:"created_by,omitempty"`
}

type _Gateway Gateway

// NewGateway instantiates a new Gateway object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGateway(name string, clusterId string, releaseId string, namespace string) *Gateway {
	this := Gateway{}
	this.Name = name
	this.ClusterId = clusterId
	this.ReleaseId = releaseId
	this.Namespace = namespace
	return &this
}

// NewGatewayWithDefaults instantiates a new Gateway object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayWithDefaults() *Gateway {
	this := Gateway{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Gateway) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Gateway) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Gateway) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Gateway) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Gateway) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Gateway) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Gateway) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Gateway) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Gateway) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Gateway) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Gateway) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Gateway) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Gateway) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Gateway) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Gateway) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value
func (o *Gateway) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Gateway) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Gateway) SetName(v string) {
	o.Name = v
}

// GetClusterId returns the ClusterId field value
func (o *Gateway) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *Gateway) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *Gateway) SetClusterId(v string) {
	o.ClusterId = v
}

// GetReleaseId returns the ReleaseId field value
func (o *Gateway) GetReleaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseId
}

// GetReleaseIdOk returns a tuple with the ReleaseId field value
// and a boolean to check if the value has been set.
func (o *Gateway) GetReleaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseId, true
}

// SetReleaseId sets field value
func (o *Gateway) SetReleaseId(v string) {
	o.ReleaseId = v
}

// GetNamespace returns the Namespace field value
func (o *Gateway) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *Gateway) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *Gateway) SetNamespace(v string) {
	o.Namespace = v
}

// GetExternalDns returns the ExternalDns field value if set, zero value otherwise.
func (o *Gateway) GetExternalDns() string {
	if o == nil || IsNil(o.ExternalDns) {
		var ret string
		return ret
	}
	return *o.ExternalDns
}

// GetExternalDnsOk returns a tuple with the ExternalDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetExternalDnsOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalDns) {
		return nil, false
	}
	return o.ExternalDns, true
}

// HasExternalDns returns a boolean if a field has been set.
func (o *Gateway) HasExternalDns() bool {
	if o != nil && !IsNil(o.ExternalDns) {
		return true
	}

	return false
}

// SetExternalDns gets a reference to the given string and assigns it to the ExternalDns field.
func (o *Gateway) SetExternalDns(v string) {
	o.ExternalDns = &v
}

// GetTlsMode returns the TlsMode field value if set, zero value otherwise.
func (o *Gateway) GetTlsMode() string {
	if o == nil || IsNil(o.TlsMode) {
		var ret string
		return ret
	}
	return *o.TlsMode
}

// GetTlsModeOk returns a tuple with the TlsMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetTlsModeOk() (*string, bool) {
	if o == nil || IsNil(o.TlsMode) {
		return nil, false
	}
	return o.TlsMode, true
}

// HasTlsMode returns a boolean if a field has been set.
func (o *Gateway) HasTlsMode() bool {
	if o != nil && !IsNil(o.TlsMode) {
		return true
	}

	return false
}

// SetTlsMode gets a reference to the given string and assigns it to the TlsMode field.
func (o *Gateway) SetTlsMode(v string) {
	o.TlsMode = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *Gateway) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *Gateway) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *Gateway) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Gateway) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Gateway) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Gateway) SetStatus(v string) {
	o.Status = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *Gateway) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *Gateway) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *Gateway) SetPhase(v string) {
	o.Phase = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Gateway) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Gateway) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *Gateway) SetImage(v string) {
	o.Image = &v
}

// GetSupervisorImage returns the SupervisorImage field value if set, zero value otherwise.
func (o *Gateway) GetSupervisorImage() string {
	if o == nil || IsNil(o.SupervisorImage) {
		var ret string
		return ret
	}
	return *o.SupervisorImage
}

// GetSupervisorImageOk returns a tuple with the SupervisorImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetSupervisorImageOk() (*string, bool) {
	if o == nil || IsNil(o.SupervisorImage) {
		return nil, false
	}
	return o.SupervisorImage, true
}

// HasSupervisorImage returns a boolean if a field has been set.
func (o *Gateway) HasSupervisorImage() bool {
	if o != nil && !IsNil(o.SupervisorImage) {
		return true
	}

	return false
}

// SetSupervisorImage gets a reference to the given string and assigns it to the SupervisorImage field.
func (o *Gateway) SetSupervisorImage(v string) {
	o.SupervisorImage = &v
}

// GetServerDnsNames returns the ServerDnsNames field value if set, zero value otherwise.
func (o *Gateway) GetServerDnsNames() []string {
	if o == nil || IsNil(o.ServerDnsNames) {
		var ret []string
		return ret
	}
	return o.ServerDnsNames
}

// GetServerDnsNamesOk returns a tuple with the ServerDnsNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetServerDnsNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerDnsNames) {
		return nil, false
	}
	return o.ServerDnsNames, true
}

// HasServerDnsNames returns a boolean if a field has been set.
func (o *Gateway) HasServerDnsNames() bool {
	if o != nil && !IsNil(o.ServerDnsNames) {
		return true
	}

	return false
}

// SetServerDnsNames gets a reference to the given []string and assigns it to the ServerDnsNames field.
func (o *Gateway) SetServerDnsNames(v []string) {
	o.ServerDnsNames = v
}

// GetRouteAddress returns the RouteAddress field value if set, zero value otherwise.
func (o *Gateway) GetRouteAddress() string {
	if o == nil || IsNil(o.RouteAddress) {
		var ret string
		return ret
	}
	return *o.RouteAddress
}

// GetRouteAddressOk returns a tuple with the RouteAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetRouteAddressOk() (*string, bool) {
	if o == nil || IsNil(o.RouteAddress) {
		return nil, false
	}
	return o.RouteAddress, true
}

// HasRouteAddress returns a boolean if a field has been set.
func (o *Gateway) HasRouteAddress() bool {
	if o != nil && !IsNil(o.RouteAddress) {
		return true
	}

	return false
}

// SetRouteAddress gets a reference to the given string and assigns it to the RouteAddress field.
func (o *Gateway) SetRouteAddress(v string) {
	o.RouteAddress = &v
}

// GetConsoleAddress returns the ConsoleAddress field value if set, zero value otherwise.
func (o *Gateway) GetConsoleAddress() string {
	if o == nil || IsNil(o.ConsoleAddress) {
		var ret string
		return ret
	}
	return *o.ConsoleAddress
}

// GetConsoleAddressOk returns a tuple with the ConsoleAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetConsoleAddressOk() (*string, bool) {
	if o == nil || IsNil(o.ConsoleAddress) {
		return nil, false
	}
	return o.ConsoleAddress, true
}

// HasConsoleAddress returns a boolean if a field has been set.
func (o *Gateway) HasConsoleAddress() bool {
	if o != nil && !IsNil(o.ConsoleAddress) {
		return true
	}

	return false
}

// SetConsoleAddress gets a reference to the given string and assigns it to the ConsoleAddress field.
func (o *Gateway) SetConsoleAddress(v string) {
	o.ConsoleAddress = &v
}

// GetGatewayVersion returns the GatewayVersion field value if set, zero value otherwise.
func (o *Gateway) GetGatewayVersion() string {
	if o == nil || IsNil(o.GatewayVersion) {
		var ret string
		return ret
	}
	return *o.GatewayVersion
}

// GetGatewayVersionOk returns a tuple with the GatewayVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetGatewayVersionOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayVersion) {
		return nil, false
	}
	return o.GatewayVersion, true
}

// HasGatewayVersion returns a boolean if a field has been set.
func (o *Gateway) HasGatewayVersion() bool {
	if o != nil && !IsNil(o.GatewayVersion) {
		return true
	}

	return false
}

// SetGatewayVersion gets a reference to the given string and assigns it to the GatewayVersion field.
func (o *Gateway) SetGatewayVersion(v string) {
	o.GatewayVersion = &v
}

// GetObservedReleaseId returns the ObservedReleaseId field value if set, zero value otherwise.
func (o *Gateway) GetObservedReleaseId() string {
	if o == nil || IsNil(o.ObservedReleaseId) {
		var ret string
		return ret
	}
	return *o.ObservedReleaseId
}

// GetObservedReleaseIdOk returns a tuple with the ObservedReleaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetObservedReleaseIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedReleaseId) {
		return nil, false
	}
	return o.ObservedReleaseId, true
}

// HasObservedReleaseId returns a boolean if a field has been set.
func (o *Gateway) HasObservedReleaseId() bool {
	if o != nil && !IsNil(o.ObservedReleaseId) {
		return true
	}

	return false
}

// SetObservedReleaseId gets a reference to the given string and assigns it to the ObservedReleaseId field.
func (o *Gateway) SetObservedReleaseId(v string) {
	o.ObservedReleaseId = &v
}

// GetOidc returns the Oidc field value if set, zero value otherwise.
func (o *Gateway) GetOidc() string {
	if o == nil || IsNil(o.Oidc) {
		var ret string
		return ret
	}
	return *o.Oidc
}

// GetOidcOk returns a tuple with the Oidc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetOidcOk() (*string, bool) {
	if o == nil || IsNil(o.Oidc) {
		return nil, false
	}
	return o.Oidc, true
}

// HasOidc returns a boolean if a field has been set.
func (o *Gateway) HasOidc() bool {
	if o != nil && !IsNil(o.Oidc) {
		return true
	}

	return false
}

// SetOidc gets a reference to the given string and assigns it to the Oidc field.
func (o *Gateway) SetOidc(v string) {
	o.Oidc = &v
}

// GetRoute returns the Route field value if set, zero value otherwise.
func (o *Gateway) GetRoute() string {
	if o == nil || IsNil(o.Route) {
		var ret string
		return ret
	}
	return *o.Route
}

// GetRouteOk returns a tuple with the Route field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetRouteOk() (*string, bool) {
	if o == nil || IsNil(o.Route) {
		return nil, false
	}
	return o.Route, true
}

// HasRoute returns a boolean if a field has been set.
func (o *Gateway) HasRoute() bool {
	if o != nil && !IsNil(o.Route) {
		return true
	}

	return false
}

// SetRoute gets a reference to the given string and assigns it to the Route field.
func (o *Gateway) SetRoute(v string) {
	o.Route = &v
}

// GetCredentialDriver returns the CredentialDriver field value if set, zero value otherwise.
func (o *Gateway) GetCredentialDriver() string {
	if o == nil || IsNil(o.CredentialDriver) {
		var ret string
		return ret
	}
	return *o.CredentialDriver
}

// GetCredentialDriverOk returns a tuple with the CredentialDriver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetCredentialDriverOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialDriver) {
		return nil, false
	}
	return o.CredentialDriver, true
}

// HasCredentialDriver returns a boolean if a field has been set.
func (o *Gateway) HasCredentialDriver() bool {
	if o != nil && !IsNil(o.CredentialDriver) {
		return true
	}

	return false
}

// SetCredentialDriver gets a reference to the given string and assigns it to the CredentialDriver field.
func (o *Gateway) SetCredentialDriver(v string) {
	o.CredentialDriver = &v
}

// GetActiveSandboxCount returns the ActiveSandboxCount field value if set, zero value otherwise.
func (o *Gateway) GetActiveSandboxCount() int32 {
	if o == nil || IsNil(o.ActiveSandboxCount) {
		var ret int32
		return ret
	}
	return *o.ActiveSandboxCount
}

// GetActiveSandboxCountOk returns a tuple with the ActiveSandboxCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetActiveSandboxCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveSandboxCount) {
		return nil, false
	}
	return o.ActiveSandboxCount, true
}

// HasActiveSandboxCount returns a boolean if a field has been set.
func (o *Gateway) HasActiveSandboxCount() bool {
	if o != nil && !IsNil(o.ActiveSandboxCount) {
		return true
	}

	return false
}

// SetActiveSandboxCount gets a reference to the given int32 and assigns it to the ActiveSandboxCount field.
func (o *Gateway) SetActiveSandboxCount(v int32) {
	o.ActiveSandboxCount = &v
}

// GetProvisioningConditions returns the ProvisioningConditions field value if set, zero value otherwise.
func (o *Gateway) GetProvisioningConditions() []GatewayAllOfProvisioningConditions {
	if o == nil || IsNil(o.ProvisioningConditions) {
		var ret []GatewayAllOfProvisioningConditions
		return ret
	}
	return o.ProvisioningConditions
}

// GetProvisioningConditionsOk returns a tuple with the ProvisioningConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetProvisioningConditionsOk() ([]GatewayAllOfProvisioningConditions, bool) {
	if o == nil || IsNil(o.ProvisioningConditions) {
		return nil, false
	}
	return o.ProvisioningConditions, true
}

// HasProvisioningConditions returns a boolean if a field has been set.
func (o *Gateway) HasProvisioningConditions() bool {
	if o != nil && !IsNil(o.ProvisioningConditions) {
		return true
	}

	return false
}

// SetProvisioningConditions gets a reference to the given []GatewayAllOfProvisioningConditions and assigns it to the ProvisioningConditions field.
func (o *Gateway) SetProvisioningConditions(v []GatewayAllOfProvisioningConditions) {
	o.ProvisioningConditions = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *Gateway) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Gateway) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *Gateway) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *Gateway) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

func (o Gateway) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Gateway) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["name"] = o.Name
	toSerialize["cluster_id"] = o.ClusterId
	toSerialize["release_id"] = o.ReleaseId
	toSerialize["namespace"] = o.Namespace
	if !IsNil(o.ExternalDns) {
		toSerialize["external_dns"] = o.ExternalDns
	}
	if !IsNil(o.TlsMode) {
		toSerialize["tls_mode"] = o.TlsMode
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.SupervisorImage) {
		toSerialize["supervisor_image"] = o.SupervisorImage
	}
	if !IsNil(o.ServerDnsNames) {
		toSerialize["server_dns_names"] = o.ServerDnsNames
	}
	if !IsNil(o.RouteAddress) {
		toSerialize["route_address"] = o.RouteAddress
	}
	if !IsNil(o.ConsoleAddress) {
		toSerialize["console_address"] = o.ConsoleAddress
	}
	if !IsNil(o.GatewayVersion) {
		toSerialize["gateway_version"] = o.GatewayVersion
	}
	if !IsNil(o.ObservedReleaseId) {
		toSerialize["observed_release_id"] = o.ObservedReleaseId
	}
	if !IsNil(o.Oidc) {
		toSerialize["oidc"] = o.Oidc
	}
	if !IsNil(o.Route) {
		toSerialize["route"] = o.Route
	}
	if !IsNil(o.CredentialDriver) {
		toSerialize["credential_driver"] = o.CredentialDriver
	}
	if !IsNil(o.ActiveSandboxCount) {
		toSerialize["active_sandbox_count"] = o.ActiveSandboxCount
	}
	if !IsNil(o.ProvisioningConditions) {
		toSerialize["provisioning_conditions"] = o.ProvisioningConditions
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	return toSerialize, nil
}

func (o *Gateway) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"cluster_id",
		"release_id",
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGateway := _Gateway{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGateway)

	if err != nil {
		return err
	}

	*o = Gateway(varGateway)

	return err
}

type NullableGateway struct {
	value *Gateway
	isSet bool
}

func (v NullableGateway) Get() *Gateway {
	return v.value
}

func (v *NullableGateway) Set(val *Gateway) {
	v.value = val
	v.isSet = true
}

func (v NullableGateway) IsSet() bool {
	return v.isSet
}

func (v *NullableGateway) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGateway(val *Gateway) *NullableGateway {
	return &NullableGateway{value: val, isSet: true}
}

func (v NullableGateway) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGateway) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
