apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.1/experimental-install.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.21.1/cert-manager.yaml
  - https://github.com/kubernetes-sigs/agent-sandbox/releases/download/v0.5.6/sandbox.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.93.1/bundle.yaml
