// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
)

type GatewayRelease struct {
	ObjectReference

	CanaryDuration  string `json:"canary_duration,omitempty"`
	CanaryPercent   int32  `json:"canary_percent,omitempty"`
	Image           string `json:"image"`
	Name            string `json:"name"`
	RolloutStrategy string `json:"rollout_strategy,omitempty"`
	Status          string `json:"status,omitempty"`
}

type GatewayReleaseList struct {
	ListMeta
	Items []GatewayRelease `json:"items"`
}

func (l *GatewayReleaseList) GetItems() []GatewayRelease { return l.Items }
func (l *GatewayReleaseList) GetTotal() int              { return l.Total }
func (l *GatewayReleaseList) GetPage() int               { return l.Page }
func (l *GatewayReleaseList) GetSize() int               { return l.Size }

type GatewayReleaseBuilder struct {
	resource GatewayRelease
	errors   []error
}

func NewGatewayReleaseBuilder() *GatewayReleaseBuilder {
	return &GatewayReleaseBuilder{}
}

func (b *GatewayReleaseBuilder) CanaryDuration(v string) *GatewayReleaseBuilder {
	b.resource.CanaryDuration = v
	return b
}

func (b *GatewayReleaseBuilder) CanaryPercent(v int32) *GatewayReleaseBuilder {
	b.resource.CanaryPercent = v
	return b
}

func (b *GatewayReleaseBuilder) Image(v string) *GatewayReleaseBuilder {
	b.resource.Image = v
	return b
}

func (b *GatewayReleaseBuilder) Name(v string) *GatewayReleaseBuilder {
	b.resource.Name = v
	return b
}

func (b *GatewayReleaseBuilder) RolloutStrategy(v string) *GatewayReleaseBuilder {
	b.resource.RolloutStrategy = v
	return b
}

func (b *GatewayReleaseBuilder) Status(v string) *GatewayReleaseBuilder {
	b.resource.Status = v
	return b
}

func (b *GatewayReleaseBuilder) Build() (*GatewayRelease, error) {
	if b.resource.Image == "" {
		b.errors = append(b.errors, fmt.Errorf("image is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type GatewayReleasePatchBuilder struct {
	patch map[string]any
}

func NewGatewayReleasePatchBuilder() *GatewayReleasePatchBuilder {
	return &GatewayReleasePatchBuilder{patch: make(map[string]any)}
}

func (b *GatewayReleasePatchBuilder) CanaryDuration(v string) *GatewayReleasePatchBuilder {
	b.patch["canary_duration"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) CanaryPercent(v int32) *GatewayReleasePatchBuilder {
	b.patch["canary_percent"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) Image(v string) *GatewayReleasePatchBuilder {
	b.patch["image"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) Name(v string) *GatewayReleasePatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) RolloutStrategy(v string) *GatewayReleasePatchBuilder {
	b.patch["rollout_strategy"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) Status(v string) *GatewayReleasePatchBuilder {
	b.patch["status"] = v
	return b
}

func (b *GatewayReleasePatchBuilder) Build() map[string]any {
	return b.patch
}
