// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
)

type GatewayNetwork struct {
	ObjectReference

	HubGatewayID string `json:"hub_gateway_id,omitempty"`
	Name         string `json:"name"`
	Status       string `json:"status,omitempty"`
	Topology     string `json:"topology,omitempty"`
	TunnelMode   string `json:"tunnel_mode,omitempty"`
}

type GatewayNetworkList struct {
	ListMeta
	Items []GatewayNetwork `json:"items"`
}

func (l *GatewayNetworkList) GetItems() []GatewayNetwork { return l.Items }
func (l *GatewayNetworkList) GetTotal() int              { return l.Total }
func (l *GatewayNetworkList) GetPage() int               { return l.Page }
func (l *GatewayNetworkList) GetSize() int               { return l.Size }

type GatewayNetworkBuilder struct {
	resource GatewayNetwork
	errors   []error
}

func NewGatewayNetworkBuilder() *GatewayNetworkBuilder {
	return &GatewayNetworkBuilder{}
}

func (b *GatewayNetworkBuilder) HubGatewayID(v string) *GatewayNetworkBuilder {
	b.resource.HubGatewayID = v
	return b
}

func (b *GatewayNetworkBuilder) Name(v string) *GatewayNetworkBuilder {
	b.resource.Name = v
	return b
}

func (b *GatewayNetworkBuilder) Status(v string) *GatewayNetworkBuilder {
	b.resource.Status = v
	return b
}

func (b *GatewayNetworkBuilder) Topology(v string) *GatewayNetworkBuilder {
	b.resource.Topology = v
	return b
}

func (b *GatewayNetworkBuilder) TunnelMode(v string) *GatewayNetworkBuilder {
	b.resource.TunnelMode = v
	return b
}

func (b *GatewayNetworkBuilder) Build() (*GatewayNetwork, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type GatewayNetworkPatchBuilder struct {
	patch map[string]any
}

func NewGatewayNetworkPatchBuilder() *GatewayNetworkPatchBuilder {
	return &GatewayNetworkPatchBuilder{patch: make(map[string]any)}
}

func (b *GatewayNetworkPatchBuilder) HubGatewayID(v string) *GatewayNetworkPatchBuilder {
	b.patch["hub_gateway_id"] = v
	return b
}

func (b *GatewayNetworkPatchBuilder) Name(v string) *GatewayNetworkPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *GatewayNetworkPatchBuilder) Status(v string) *GatewayNetworkPatchBuilder {
	b.patch["status"] = v
	return b
}

func (b *GatewayNetworkPatchBuilder) Topology(v string) *GatewayNetworkPatchBuilder {
	b.patch["topology"] = v
	return b
}

func (b *GatewayNetworkPatchBuilder) TunnelMode(v string) *GatewayNetworkPatchBuilder {
	b.patch["tunnel_mode"] = v
	return b
}

func (b *GatewayNetworkPatchBuilder) Build() map[string]any {
	return b.patch
}
