// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
	"time"
)

type ManagedCluster struct {
	ObjectReference

	APIServerURL     string     `json:"api_server_url,omitempty"`
	KubeconfigSecret string     `json:"kubeconfig_secret"`
	LastSeenAt       *time.Time `json:"last_seen_at,omitempty"`
	Name             string     `json:"name"`
	OidcSubject      string     `json:"oidc_subject,omitempty"`
	Provider         string     `json:"provider"`
	Region           string     `json:"region,omitempty"`
	Status           string     `json:"status,omitempty"`
}

type ManagedClusterList struct {
	ListMeta
	Items []ManagedCluster `json:"items"`
}

func (l *ManagedClusterList) GetItems() []ManagedCluster { return l.Items }
func (l *ManagedClusterList) GetTotal() int              { return l.Total }
func (l *ManagedClusterList) GetPage() int               { return l.Page }
func (l *ManagedClusterList) GetSize() int               { return l.Size }

type ManagedClusterBuilder struct {
	resource ManagedCluster
	errors   []error
}

func NewManagedClusterBuilder() *ManagedClusterBuilder {
	return &ManagedClusterBuilder{}
}

func (b *ManagedClusterBuilder) APIServerURL(v string) *ManagedClusterBuilder {
	b.resource.APIServerURL = v
	return b
}

func (b *ManagedClusterBuilder) KubeconfigSecret(v string) *ManagedClusterBuilder {
	b.resource.KubeconfigSecret = v
	return b
}

func (b *ManagedClusterBuilder) Name(v string) *ManagedClusterBuilder {
	b.resource.Name = v
	return b
}

func (b *ManagedClusterBuilder) Provider(v string) *ManagedClusterBuilder {
	b.resource.Provider = v
	return b
}

func (b *ManagedClusterBuilder) Region(v string) *ManagedClusterBuilder {
	b.resource.Region = v
	return b
}

func (b *ManagedClusterBuilder) Status(v string) *ManagedClusterBuilder {
	b.resource.Status = v
	return b
}

func (b *ManagedClusterBuilder) Build() (*ManagedCluster, error) {
	if b.resource.KubeconfigSecret == "" {
		b.errors = append(b.errors, fmt.Errorf("kubeconfig_secret is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Provider == "" {
		b.errors = append(b.errors, fmt.Errorf("provider is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ManagedClusterPatchBuilder struct {
	patch map[string]any
}

func NewManagedClusterPatchBuilder() *ManagedClusterPatchBuilder {
	return &ManagedClusterPatchBuilder{patch: make(map[string]any)}
}

func (b *ManagedClusterPatchBuilder) APIServerURL(v string) *ManagedClusterPatchBuilder {
	b.patch["api_server_url"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) KubeconfigSecret(v string) *ManagedClusterPatchBuilder {
	b.patch["kubeconfig_secret"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) Name(v string) *ManagedClusterPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) Provider(v string) *ManagedClusterPatchBuilder {
	b.patch["provider"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) Region(v string) *ManagedClusterPatchBuilder {
	b.patch["region"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) Status(v string) *ManagedClusterPatchBuilder {
	b.patch["status"] = v
	return b
}

func (b *ManagedClusterPatchBuilder) Build() map[string]any {
	return b.patch
}
