// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import "time"

type OpenShellGatewayServiceAccountCapabilities struct {
	AllowedRoles     []OpenShellGatewayServiceAccountRole           `json:"allowed_roles"`
	CanCreate        bool                                           `json:"can_create"`
	CanManageAll     bool                                           `json:"can_manage_all"`
	ExpirationPolicy OpenShellGatewayServiceAccountExpirationPolicy `json:"expiration_policy"`
}

type OpenShellGatewayServiceAccountConnection struct {
	AccessTokenLifetimeSeconds int    `json:"access_token_lifetime_seconds"`
	Audience                   string `json:"audience"`
	ClientID                   string `json:"client_id"`
	GatewayEndpoint            string `json:"gateway_endpoint,omitempty"`
	GatewayName                string `json:"gateway_name"`
	GrantType                  string `json:"grant_type"`
	Issuer                     string `json:"issuer"`
	TokenEndpoint              string `json:"token_endpoint"`
}

type OpenShellGatewayServiceAccountCreateRequest struct {
	CredentialType string                             `json:"credential_type,omitempty"`
	Description    *string                            `json:"description,omitempty"`
	ExpiresAt      *time.Time                         `json:"expires_at,omitempty"`
	Name           string                             `json:"name"`
	Role           OpenShellGatewayServiceAccountRole `json:"role,omitempty"`
}

type OpenShellGatewayServiceAccountCreateResponse struct {
	ClientID        string                                   `json:"client_id"`
	CreatedAt       time.Time                                `json:"created_at"`
	CreatedByUserID string                                   `json:"created_by_user_id"`
	Credential      OpenShellGatewayServiceAccountCredential `json:"credential"`
	CredentialType  string                                   `json:"credential_type"`
	Description     *string                                  `json:"description,omitempty"`
	ExpiresAt       time.Time                                `json:"expires_at"`
	GatewayID       string                                   `json:"gateway_id"`
	ID              string                                   `json:"id"`
	LastError       *string                                  `json:"last_error,omitempty"`
	Name            string                                   `json:"name"`
	RevokedAt       *time.Time                               `json:"revoked_at,omitempty"`
	Role            OpenShellGatewayServiceAccountRole       `json:"role"`
	Status          OpenShellGatewayServiceAccountStatus     `json:"status"`
	Subject         string                                   `json:"subject"`
	UpdatedAt       time.Time                                `json:"updated_at"`
}

// String deliberately omits all values because this response contains a one-time credential.
func (v OpenShellGatewayServiceAccountCreateResponse) String() string {
	return "OpenShellGatewayServiceAccountCreateResponse{[REDACTED]}"
}

// GoString prevents %#v debug formatting from exposing the one-time credential.
func (v OpenShellGatewayServiceAccountCreateResponse) GoString() string { return v.String() }

type OpenShellGatewayServiceAccountCredential struct {
	AccessTokenLifetimeSeconds int    `json:"access_token_lifetime_seconds"`
	Audience                   string `json:"audience"`
	ClientID                   string `json:"client_id"`
	ClientSecret               string `json:"client_secret"`
	GatewayEndpoint            string `json:"gateway_endpoint,omitempty"`
	GatewayName                string `json:"gateway_name"`
	GrantType                  string `json:"grant_type"`
	Issuer                     string `json:"issuer"`
	TokenEndpoint              string `json:"token_endpoint"`
}

// String deliberately omits all values because this response contains a one-time credential.
func (v OpenShellGatewayServiceAccountCredential) String() string {
	return "OpenShellGatewayServiceAccountCredential{[REDACTED]}"
}

// GoString prevents %#v debug formatting from exposing the one-time credential.
func (v OpenShellGatewayServiceAccountCredential) GoString() string { return v.String() }

type OpenShellGatewayServiceAccountExpirationPolicy struct {
	DefaultSeconds int `json:"default_seconds"`
	MaximumSeconds int `json:"maximum_seconds"`
	MinimumSeconds int `json:"minimum_seconds"`
}

type OpenShellGatewayServiceAccountGetResponse struct {
	ClientID        string                                   `json:"client_id"`
	Connection      OpenShellGatewayServiceAccountConnection `json:"connection"`
	CreatedAt       time.Time                                `json:"created_at"`
	CreatedByUserID string                                   `json:"created_by_user_id"`
	CredentialType  string                                   `json:"credential_type"`
	Description     *string                                  `json:"description,omitempty"`
	ExpiresAt       time.Time                                `json:"expires_at"`
	GatewayID       string                                   `json:"gateway_id"`
	ID              string                                   `json:"id"`
	LastError       *string                                  `json:"last_error,omitempty"`
	Name            string                                   `json:"name"`
	RevokedAt       *time.Time                               `json:"revoked_at,omitempty"`
	Role            OpenShellGatewayServiceAccountRole       `json:"role"`
	Status          OpenShellGatewayServiceAccountStatus     `json:"status"`
	Subject         string                                   `json:"subject"`
	UpdatedAt       time.Time                                `json:"updated_at"`
}

type OpenShellGatewayServiceAccountList struct {
	Capabilities OpenShellGatewayServiceAccountCapabilities `json:"capabilities"`
	Items        []OpenShellGatewayServiceAccountListItem   `json:"items"`
	Page         int                                        `json:"page"`
	Size         int                                        `json:"size"`
	Total        int                                        `json:"total"`
}

type OpenShellGatewayServiceAccountListItem struct {
	ClientID        string                               `json:"client_id"`
	CreatedAt       time.Time                            `json:"created_at"`
	CreatedByUserID string                               `json:"created_by_user_id"`
	CredentialType  string                               `json:"credential_type"`
	Description     *string                              `json:"description,omitempty"`
	ExpiresAt       time.Time                            `json:"expires_at"`
	GatewayID       string                               `json:"gateway_id"`
	ID              string                               `json:"id"`
	LastError       *string                              `json:"last_error,omitempty"`
	Name            string                               `json:"name"`
	RevokedAt       *time.Time                           `json:"revoked_at,omitempty"`
	Role            OpenShellGatewayServiceAccountRole   `json:"role"`
	Status          OpenShellGatewayServiceAccountStatus `json:"status"`
	Subject         string                               `json:"subject"`
	UpdatedAt       time.Time                            `json:"updated_at"`
}

type OpenShellGatewayServiceAccountRole string

const (
	OpenShellGatewayServiceAccountRoleOpenshellUser  OpenShellGatewayServiceAccountRole = "openshell-user"
	OpenShellGatewayServiceAccountRoleOpenshellAdmin OpenShellGatewayServiceAccountRole = "openshell-admin"
)

type OpenShellGatewayServiceAccountStatus string

const (
	OpenShellGatewayServiceAccountStatusProvisioning OpenShellGatewayServiceAccountStatus = "provisioning"
	OpenShellGatewayServiceAccountStatusReady        OpenShellGatewayServiceAccountStatus = "ready"
	OpenShellGatewayServiceAccountStatusDegraded     OpenShellGatewayServiceAccountStatus = "degraded"
	OpenShellGatewayServiceAccountStatusExpired      OpenShellGatewayServiceAccountStatus = "expired"
	OpenShellGatewayServiceAccountStatusRevoking     OpenShellGatewayServiceAccountStatus = "revoking"
	OpenShellGatewayServiceAccountStatusRevoked      OpenShellGatewayServiceAccountStatus = "revoked"
	OpenShellGatewayServiceAccountStatusDeleting     OpenShellGatewayServiceAccountStatus = "deleting"
	OpenShellGatewayServiceAccountStatusError        OpenShellGatewayServiceAccountStatus = "error"
)

func (l *OpenShellGatewayServiceAccountList) GetItems() []OpenShellGatewayServiceAccountListItem {
	return l.Items
}
func (l *OpenShellGatewayServiceAccountList) GetTotal() int { return l.Total }
func (l *OpenShellGatewayServiceAccountList) GetPage() int  { return l.Page }
func (l *OpenShellGatewayServiceAccountList) GetSize() int  { return l.Size }

type OpenShellGatewayServiceAccountListOptions struct {
	Page   int
	Size   int
	Status OpenShellGatewayServiceAccountStatus
	Search string
	Sort   string
	Order  string
}

type OpenShellGatewayServiceAccountListOptionsBuilder struct {
	opts OpenShellGatewayServiceAccountListOptions
}

func NewOpenShellGatewayServiceAccountListOptions() *OpenShellGatewayServiceAccountListOptionsBuilder {
	return &OpenShellGatewayServiceAccountListOptionsBuilder{opts: OpenShellGatewayServiceAccountListOptions{Page: 1, Size: 20}}
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Page(value int) *OpenShellGatewayServiceAccountListOptionsBuilder {
	b.opts.Page = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Size(value int) *OpenShellGatewayServiceAccountListOptionsBuilder {
	if value > 100 {
		value = 100
	}
	b.opts.Size = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Status(value OpenShellGatewayServiceAccountStatus) *OpenShellGatewayServiceAccountListOptionsBuilder {
	b.opts.Status = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Search(value string) *OpenShellGatewayServiceAccountListOptionsBuilder {
	b.opts.Search = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Sort(value string) *OpenShellGatewayServiceAccountListOptionsBuilder {
	b.opts.Sort = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Order(value string) *OpenShellGatewayServiceAccountListOptionsBuilder {
	b.opts.Order = value
	return b
}

func (b *OpenShellGatewayServiceAccountListOptionsBuilder) Build() *OpenShellGatewayServiceAccountListOptions {
	return &b.opts
}
