// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
)

type Role struct {
	ObjectReference

	BuiltIn     bool   `json:"built_in,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Name        string `json:"name"`
	Permissions string `json:"permissions,omitempty"`
}

type RoleList struct {
	ListMeta
	Items []Role `json:"items"`
}

func (l *RoleList) GetItems() []Role { return l.Items }
func (l *RoleList) GetTotal() int    { return l.Total }
func (l *RoleList) GetPage() int     { return l.Page }
func (l *RoleList) GetSize() int     { return l.Size }

type RoleBuilder struct {
	resource Role
	errors   []error
}

func NewRoleBuilder() *RoleBuilder {
	return &RoleBuilder{}
}

func (b *RoleBuilder) BuiltIn(v bool) *RoleBuilder {
	b.resource.BuiltIn = v
	return b
}

func (b *RoleBuilder) Description(v string) *RoleBuilder {
	b.resource.Description = v
	return b
}

func (b *RoleBuilder) DisplayName(v string) *RoleBuilder {
	b.resource.DisplayName = v
	return b
}

func (b *RoleBuilder) Name(v string) *RoleBuilder {
	b.resource.Name = v
	return b
}

func (b *RoleBuilder) Permissions(v string) *RoleBuilder {
	b.resource.Permissions = v
	return b
}

func (b *RoleBuilder) Build() (*Role, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type RolePatchBuilder struct {
	patch map[string]any
}

func NewRolePatchBuilder() *RolePatchBuilder {
	return &RolePatchBuilder{patch: make(map[string]any)}
}

func (b *RolePatchBuilder) Build() map[string]any {
	return b.patch
}
