// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
)

type RoleBinding struct {
	ObjectReference

	GatewayID string `json:"gateway_id,omitempty"`
	RoleID    string `json:"role_id"`
	Scope     string `json:"scope"`
	UserID    string `json:"user_id,omitempty"`
}

type RoleBindingList struct {
	ListMeta
	Items []RoleBinding `json:"items"`
}

func (l *RoleBindingList) GetItems() []RoleBinding { return l.Items }
func (l *RoleBindingList) GetTotal() int           { return l.Total }
func (l *RoleBindingList) GetPage() int            { return l.Page }
func (l *RoleBindingList) GetSize() int            { return l.Size }

type RoleBindingBuilder struct {
	resource RoleBinding
	errors   []error
}

func NewRoleBindingBuilder() *RoleBindingBuilder {
	return &RoleBindingBuilder{}
}

func (b *RoleBindingBuilder) GatewayID(v string) *RoleBindingBuilder {
	b.resource.GatewayID = v
	return b
}

func (b *RoleBindingBuilder) RoleID(v string) *RoleBindingBuilder {
	b.resource.RoleID = v
	return b
}

func (b *RoleBindingBuilder) Scope(v string) *RoleBindingBuilder {
	b.resource.Scope = v
	return b
}

func (b *RoleBindingBuilder) UserID(v string) *RoleBindingBuilder {
	b.resource.UserID = v
	return b
}

func (b *RoleBindingBuilder) Build() (*RoleBinding, error) {
	if b.resource.RoleID == "" {
		b.errors = append(b.errors, fmt.Errorf("role_id is required"))
	}
	if b.resource.Scope == "" {
		b.errors = append(b.errors, fmt.Errorf("scope is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type RoleBindingPatchBuilder struct {
	patch map[string]any
}

func NewRoleBindingPatchBuilder() *RoleBindingPatchBuilder {
	return &RoleBindingPatchBuilder{patch: make(map[string]any)}
}

func (b *RoleBindingPatchBuilder) Build() map[string]any {
	return b.patch
}
