// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package types

import (
	"errors"
	"fmt"
)

type User struct {
	ObjectReference

	Email    string `json:"email,omitempty"`
	Name     string `json:"name,omitempty"`
	Username string `json:"username"`
}

type UserList struct {
	ListMeta
	Items []User `json:"items"`
}

func (l *UserList) GetItems() []User { return l.Items }
func (l *UserList) GetTotal() int    { return l.Total }
func (l *UserList) GetPage() int     { return l.Page }
func (l *UserList) GetSize() int     { return l.Size }

type UserBuilder struct {
	resource User
	errors   []error
}

func NewUserBuilder() *UserBuilder {
	return &UserBuilder{}
}

func (b *UserBuilder) Email(v string) *UserBuilder {
	b.resource.Email = v
	return b
}

func (b *UserBuilder) Name(v string) *UserBuilder {
	b.resource.Name = v
	return b
}

func (b *UserBuilder) Username(v string) *UserBuilder {
	b.resource.Username = v
	return b
}

func (b *UserBuilder) Build() (*User, error) {
	if b.resource.Username == "" {
		b.errors = append(b.errors, fmt.Errorf("username is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type UserPatchBuilder struct {
	patch map[string]any
}

func NewUserPatchBuilder() *UserPatchBuilder {
	return &UserPatchBuilder{patch: make(map[string]any)}
}

func (b *UserPatchBuilder) Build() map[string]any {
	return b.patch
}
