// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type Client struct {
	httpClient *http.Client
	baseURL    string
	token      string
	logger     *slog.Logger
	userAgent  string
}

type ClientOption func(*Client)

func WithTimeout(timeout time.Duration) ClientOption {
	return func(c *Client) {
		c.httpClient.Timeout = timeout
	}
}

func WithLogger(logger *slog.Logger) ClientOption {
	return func(c *Client) {
		c.logger = logger
	}
}

func WithUserAgent(userAgent string) ClientOption {
	return func(c *Client) {
		c.userAgent = userAgent
	}
}

func NewClient(baseURL, token string, opts ...ClientOption) (*Client, error) {
	if token == "" {
		return nil, fmt.Errorf("token is required")
	}

	if err := validateURL(baseURL); err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	c := &Client{
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
		baseURL:   strings.TrimSuffix(baseURL, "/"),
		token:     token,
		logger:    slog.Default(),
		userAgent: "hypershell-go-sdk/1.0.0",
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

func NewClientFromEnv(opts ...ClientOption) (*Client, error) {
	baseURL := os.Getenv("API_URL")
	if baseURL == "" {
		baseURL = "https://localhost:8000"
	}

	token := os.Getenv("API_TOKEN")
	if token == "" {
		return nil, fmt.Errorf("API_TOKEN environment variable is required")
	}

	return NewClient(baseURL, token, opts...)
}

func (c *Client) do(ctx context.Context, method, path string, body []byte, expectedStatus int, result interface{}) error {
	_, err := c.doAny(ctx, method, path, body, result, expectedStatus)
	return err
}

func (c *Client) doAny(ctx context.Context, method, path string, body []byte, result interface{}, expectedStatuses ...int) (int, error) {
	reqURL := c.baseURL + "/api/hypershell/v1" + path

	req, err := http.NewRequestWithContext(ctx, method, reqURL, nil)
	if err != nil {
		return 0, fmt.Errorf("create request: %w", err)
	}

	if body != nil {
		req.Body = io.NopCloser(bytes.NewReader(body))
		req.ContentLength = int64(len(body))
		req.Header.Set("Content-Type", "application/json")
	}

	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("User-Agent", c.userAgent)
	req.Header.Set("Accept", "application/json")

	c.logger.Debug("HTTP request",
		slog.String("method", method),
		slog.String("url", sanitizeLogURL(reqURL)),
		slog.Int("body_len", len(body)),
	)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return 0, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	// Limit response body size to 10MB to prevent memory exhaustion attacks
	limitedReader := io.LimitReader(resp.Body, 10*1024*1024)
	respBody, err := io.ReadAll(limitedReader)
	if err != nil {
		return resp.StatusCode, fmt.Errorf("read response body: %w", err)
	}

	c.logger.Debug("HTTP response",
		slog.Int("status", resp.StatusCode),
		slog.Int("body_len", len(respBody)),
	)

	expected := false
	for _, status := range expectedStatuses {
		if resp.StatusCode == status {
			expected = true
			break
		}
	}
	if !expected {
		var apiErr types.APIError
		if json.Unmarshal(respBody, &apiErr) == nil && apiErr.Code != "" {
			apiErr.StatusCode = resp.StatusCode
			return resp.StatusCode, &apiErr
		}
		return resp.StatusCode, &types.APIError{
			StatusCode: resp.StatusCode,
			Code:       "http_error",
			Reason:     fmt.Sprintf("HTTP %d: unexpected status", resp.StatusCode),
		}
	}

	if result != nil && len(respBody) > 0 {
		if err := json.Unmarshal(respBody, result); err != nil {
			return resp.StatusCode, fmt.Errorf("unmarshal response: %w", err)
		}
	}

	return resp.StatusCode, nil
}

func (c *Client) doWithQuery(ctx context.Context, method, path string, body []byte, expectedStatus int, result interface{}, opts *types.ListOptions) error {
	queryPath := path
	if opts != nil {
		params := url.Values{}
		if opts.Page > 0 {
			params.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.Size > 0 {
			params.Set("size", fmt.Sprintf("%d", opts.Size))
		}
		if opts.Search != "" {
			params.Set("search", opts.Search)
		}
		if opts.OrderBy != "" {
			params.Set("orderBy", opts.OrderBy)
		}
		if opts.Fields != "" {
			params.Set("fields", opts.Fields)
		}
		if len(params) > 0 {
			queryPath += "?" + params.Encode()
		}
	}

	return c.do(ctx, method, queryPath, body, expectedStatus, result)
}

func validateURL(rawURL string) error {
	if rawURL == "" {
		return fmt.Errorf("URL cannot be empty")
	}

	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Errorf("invalid URL format: %w", err)
	}

	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("only HTTP and HTTPS schemes are supported")
	}

	return nil
}

func sanitizeLogURL(rawURL string) string {
	tokenPattern := regexp.MustCompile(`([Bb]earer\s+)[a-zA-Z0-9\-_~.+/=]+`)
	return tokenPattern.ReplaceAllString(rawURL, "${1}[REDACTED]")
}
