// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type GatewayReleaseAPI struct {
	client *Client
}

func (c *Client) GatewayReleases() *GatewayReleaseAPI {
	return &GatewayReleaseAPI{client: c}
}

func (a *GatewayReleaseAPI) Create(ctx context.Context, resource *types.GatewayRelease) (*types.GatewayRelease, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal gateway_release: %w", err)
	}
	var result types.GatewayRelease
	if err := a.client.do(ctx, http.MethodPost, "/gateway_releases", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayReleaseAPI) Get(ctx context.Context, id string) (*types.GatewayRelease, error) {
	var result types.GatewayRelease
	if err := a.client.do(ctx, http.MethodGet, "/gateway_releases/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayReleaseAPI) List(ctx context.Context, opts *types.ListOptions) (*types.GatewayReleaseList, error) {
	var result types.GatewayReleaseList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/gateway_releases", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayReleaseAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.GatewayRelease, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.GatewayRelease
	if err := a.client.do(ctx, http.MethodPatch, "/gateway_releases/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayReleaseAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/gateway_releases/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *GatewayReleaseAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.GatewayRelease] {
	return NewIterator(func(page int) (*types.GatewayReleaseList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
