// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type GatewayNetworkAPI struct {
	client *Client
}

func (c *Client) GatewayNetworks() *GatewayNetworkAPI {
	return &GatewayNetworkAPI{client: c}
}

func (a *GatewayNetworkAPI) Create(ctx context.Context, resource *types.GatewayNetwork) (*types.GatewayNetwork, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal gateway_network: %w", err)
	}
	var result types.GatewayNetwork
	if err := a.client.do(ctx, http.MethodPost, "/gateway_networks", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayNetworkAPI) Get(ctx context.Context, id string) (*types.GatewayNetwork, error) {
	var result types.GatewayNetwork
	if err := a.client.do(ctx, http.MethodGet, "/gateway_networks/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayNetworkAPI) List(ctx context.Context, opts *types.ListOptions) (*types.GatewayNetworkList, error) {
	var result types.GatewayNetworkList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/gateway_networks", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayNetworkAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.GatewayNetwork, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.GatewayNetwork
	if err := a.client.do(ctx, http.MethodPatch, "/gateway_networks/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayNetworkAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/gateway_networks/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *GatewayNetworkAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.GatewayNetwork] {
	return NewIterator(func(page int) (*types.GatewayNetworkList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
