// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type ManagedClusterAPI struct {
	client *Client
}

func (c *Client) ManagedClusters() *ManagedClusterAPI {
	return &ManagedClusterAPI{client: c}
}

func (a *ManagedClusterAPI) Create(ctx context.Context, resource *types.ManagedCluster) (*types.ManagedCluster, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal managed_cluster: %w", err)
	}
	var result types.ManagedCluster
	if err := a.client.do(ctx, http.MethodPost, "/managed_clusters", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedClusterAPI) Get(ctx context.Context, id string) (*types.ManagedCluster, error) {
	var result types.ManagedCluster
	if err := a.client.do(ctx, http.MethodGet, "/managed_clusters/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedClusterAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ManagedClusterList, error) {
	var result types.ManagedClusterList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/managed_clusters", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedClusterAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ManagedCluster, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ManagedCluster
	if err := a.client.do(ctx, http.MethodPatch, "/managed_clusters/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedClusterAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/managed_clusters/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ManagedClusterAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ManagedCluster] {
	return NewIterator(func(page int) (*types.ManagedClusterList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
