// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type OpenShellGatewayServiceAccountAPI struct {
	client *Client
}

func (c *Client) OpenShellGatewayServiceAccounts() *OpenShellGatewayServiceAccountAPI {
	return &OpenShellGatewayServiceAccountAPI{client: c}
}

func (a *OpenShellGatewayServiceAccountAPI) Create(ctx context.Context, gatewayID string, request *types.OpenShellGatewayServiceAccountCreateRequest) (*types.OpenShellGatewayServiceAccountCreateResponse, error) {
	body, err := json.Marshal(request)
	if err != nil {
		return nil, fmt.Errorf("marshal open_shell_gateway_service_account create request: %w", err)
	}
	var result types.OpenShellGatewayServiceAccountCreateResponse
	if _, err := a.client.doAny(ctx, http.MethodPost, fmt.Sprintf("/gateways/%s/service_accounts", url.PathEscape(gatewayID)), body, &result, http.StatusCreated); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *OpenShellGatewayServiceAccountAPI) Get(ctx context.Context, gatewayID string, serviceAccountID string) (*types.OpenShellGatewayServiceAccountGetResponse, error) {
	var result types.OpenShellGatewayServiceAccountGetResponse
	if _, err := a.client.doAny(ctx, http.MethodGet, fmt.Sprintf("/gateways/%s/service_accounts/%s", url.PathEscape(gatewayID), url.PathEscape(serviceAccountID)), nil, &result, http.StatusOK); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *OpenShellGatewayServiceAccountAPI) List(ctx context.Context, gatewayID string, opts *types.OpenShellGatewayServiceAccountListOptions) (*types.OpenShellGatewayServiceAccountList, error) {
	path := fmt.Sprintf("/gateways/%s/service_accounts", url.PathEscape(gatewayID))
	if opts != nil {
		params := url.Values{}
		if opts.Page > 0 {
			params.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.Size > 0 {
			params.Set("size", fmt.Sprintf("%d", opts.Size))
		}
		if opts.Status != "" {
			params.Set("status", string(opts.Status))
		}
		if opts.Search != "" {
			params.Set("search", string(opts.Search))
		}
		if opts.Sort != "" {
			params.Set("sort", string(opts.Sort))
		}
		if opts.Order != "" {
			params.Set("order", string(opts.Order))
		}
		if len(params) > 0 {
			path += "?" + params.Encode()
		}
	}
	var result types.OpenShellGatewayServiceAccountList
	if _, err := a.client.doAny(ctx, http.MethodGet, path, nil, &result, http.StatusOK); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *OpenShellGatewayServiceAccountAPI) Revoke(ctx context.Context, gatewayID string, serviceAccountID string) (*types.OpenShellGatewayServiceAccountListItem, error) {
	var result types.OpenShellGatewayServiceAccountListItem
	if _, err := a.client.doAny(ctx, http.MethodPost, fmt.Sprintf("/gateways/%s/service_accounts/%s", url.PathEscape(gatewayID), url.PathEscape(serviceAccountID))+"/revoke", nil, &result, http.StatusOK, http.StatusAccepted); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *OpenShellGatewayServiceAccountAPI) Delete(ctx context.Context, gatewayID string, serviceAccountID string) (*types.OpenShellGatewayServiceAccountListItem, error) {
	var result types.OpenShellGatewayServiceAccountListItem
	status, err := a.client.doAny(ctx, http.MethodDelete, fmt.Sprintf("/gateways/%s/service_accounts/%s", url.PathEscape(gatewayID), url.PathEscape(serviceAccountID)), nil, &result, http.StatusNoContent, http.StatusAccepted)
	if err != nil {
		return nil, err
	}
	if status == http.StatusNoContent {
		return nil, nil
	}
	return &result, nil
}

func (a *OpenShellGatewayServiceAccountAPI) ListAll(ctx context.Context, gatewayID string, opts *types.OpenShellGatewayServiceAccountListOptions) *Iterator[types.OpenShellGatewayServiceAccountListItem] {
	if opts == nil {
		opts = types.NewOpenShellGatewayServiceAccountListOptions().Build()
	}
	return NewIterator(func(page int) (*types.OpenShellGatewayServiceAccountList, error) {
		copyOpts := *opts
		copyOpts.Page = page
		return a.List(ctx, gatewayID, &copyOpts)
	})
}
