// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type RoleBindingAPI struct {
	client *Client
}

func (c *Client) RoleBindings() *RoleBindingAPI {
	return &RoleBindingAPI{client: c}
}

func (a *RoleBindingAPI) Create(ctx context.Context, resource *types.RoleBinding) (*types.RoleBinding, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal role_binding: %w", err)
	}
	var result types.RoleBinding
	if err := a.client.do(ctx, http.MethodPost, "/role_bindings", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleBindingAPI) Get(ctx context.Context, id string) (*types.RoleBinding, error) {
	var result types.RoleBinding
	if err := a.client.do(ctx, http.MethodGet, "/role_bindings/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleBindingAPI) List(ctx context.Context, opts *types.ListOptions) (*types.RoleBindingList, error) {
	var result types.RoleBindingList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/role_bindings", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleBindingAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/role_bindings/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *RoleBindingAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.RoleBinding] {
	return NewIterator(func(page int) (*types.RoleBindingList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
