// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: a235ac311650fdf575f024fea0fefefd2dedd70b90a44e76c641945fed5fa917

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type UserAPI struct {
	client *Client
}

func (c *Client) Users() *UserAPI {
	return &UserAPI{client: c}
}

func (a *UserAPI) Create(ctx context.Context, resource *types.User) (*types.User, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal user: %w", err)
	}
	var result types.User
	if err := a.client.do(ctx, http.MethodPost, "/users", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) Get(ctx context.Context, id string) (*types.User, error) {
	var result types.User
	if err := a.client.do(ctx, http.MethodGet, "/users/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) List(ctx context.Context, opts *types.ListOptions) (*types.UserList, error) {
	var result types.UserList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/users", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.User] {
	return NewIterator(func(page int) (*types.UserList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
